config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users
  namespace :admin  do
    root "static_pages#home"
    resources :users
    resources :categories
    resources :words
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :lessons
  has_many :words, dependent: :destroy

  validates :name, presence: true
  validates :description, length: {maximum: 200}

  def verify_destroy?
    !self.lessons.any?
  end

  scope :search, ->keyword { where "name LIKE ?", "%#{keyword}%" }

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :logged_in_user
  before_action :verify_admin
  before_action :load_category, only: [:destroy, :edit, :update]

  def index
    if params[:key]
      @categories = Category.search params[:key]
      respond_to do |format|
        format.json do
          render json: @categories
        end
      end
    elsif params[:category_search]
      @categories = Category.search(params[:category_search]).
        paginate page: params[:page],
        per_page: Settings.per_page
    else
      @categories = Category.all.paginate page: params[:page],
        per_page: Settings.per_page
    end
    @category = Category.new
  end

  def edit
  end

  def new
  end

  def create
    @category = Category.new category_params
    if @category.save
      respond_to do |format|
        format.html do
          flash[:success] = t "create_success"
          redirect_to admin_categories_path
        end
        format.json do
          render json: @category
        end
      end
    else
      flash[:danger] = t "create_failed"
      redirect_to admin_categories_path
    end
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t "update_success"
      redirect_to admin_categories_path
    else
      flash[:danger] = t "update_failed"
      render :edit
    end
  end

  def destroy
    respond_to do |format|
      if @category.verify_destroy?
        @category.destroy
        format.json do
          render json: {status: @category.destroyed?}
        end
      end
    end
  end

  private

  def category_params
    params.require(:category).permit :name, :description
  end

  def load_category
    @category = Category.find_by id: params[:id]
    if @category.nil?
      flash[:danger] = t "category_not_found"
      redirect_to admin_categories_path
    end
  end
end

app/views/admin/categories/_new.html.erb
<div class="modal fade new-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"
          aria-hidden="true">&times;</button>
        <h4 class="modal-title text-center"><%= t "new_category" %></h4>
      </div>
      <%= form_for [:admin, @category], remote: true do |f| %>
        <div class="modal-body">
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group">
          <%= f.label :description %>
            <%= f.text_area :description, class: "form-control" %>
          </div>
        </div>
        <div class="modal-footer">
          <%= f.submit t(".add"), class: "btn btn-primary", id: "btn-submit" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/categories/edit.html.erb
<div class="row box">
  <div class="col-md-6 col-md-offset-3">
  <h1><%= t "edit_category" %></h1>
  <%= form_for [:admin, @category] do |f| %>
    <%= render "shared/error_messages", object: f.object %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit t(".edit"), class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/admin/categories/index.html.erb
<% provide :title, (t ".allcategory") %>
<h1><%= t ".allcategory" %></h1>
<%= form_tag admin_categories_path, method: :get do %>
  <div class="form-group row">
    <div class="col-xs-8">
      <div class="search">
        <h4><%= t ".search" %></h4>
      </div>
    </div>
    <div class="col-xs-4">
      <%= text_field_tag :category_search, params[:search], class: "form-control" %>
    </div>
  </div>
<% end %>
<div>
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".new-modal"><%= t "new" %></button>
</div>
</br>
<table class="table table-hover bg-table ls-users">
  <thead class="title_table">
    <tr>
      <th class="text-c"><%= t ".name" %></th>
      <th class="text-c"><%= t ".description" %></th>
      <th class="text-c"><%= t ".word" %></th>
      <th class="text-c"><%= t ".edit" %></th>
      <th class="text-c"><%= t ".delete" %></th>
    </tr>
  </thead>
  <tbody id ="result_search">
    <% @categories.each.with_index do |category| %>
      <tr id="category-<%= category.id %>">
        <td class="text-c"><%= category.name %></td>
        <td class="text-c"><%= category.description %></td>
        <td class="text-c">
          <button class = "btn btn-default glyphicon glyphicon-book">
          <%=t ".word"%>
          </button>
        </td>
        <td>
          <%= link_to t("edit"), edit_admin_category_path(category.id),
        class: "btn btn-default glyphicon glyphicon-pencil" %>
        </td>
        <td class="text-c">
            <button class = "danger btn btn-default glyphicon glyphicon-trash
              delete-category"
              onclick = "delCategory(<%= category.id %>)">
            <%= t".delete"%>
          </button>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate %>
<%= render "new" %>