config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users
  namespace :admin  do
    root "static_pages#home"
    resources :users
    resources :categories
    resources :words
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <h6><%= t".content" %></h6>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(".framgiaELearning"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t(".home"), root_path %></li>
        <li><%= link_to t(".help"), help_path %></li>
        <% if logged_in? %>
          <% if is_admin? %>
            <li class="dropdown">
              <%= link_to "#", class: "dropdown-toggle", "data-toggle":
                "dropdown" do %>
                <%= t ".manage" %>
                <span class="caret"></span>
              <% end %>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to t(".user"), admin_users_path,
                    data: {turbolinks: false} %>
                </li>
                <li>
                  <%= link_to t(".catergory"), admin_categories_path,
                    data: {turbolinks: false} %>
                </li>
                <li>
                  <%= link_to t(".word"), admin_words_path,
                    data: {turbolinks: false} %>
                </li>
              </ul>
            </li>
          <% end %>
          <li>
            <%= link_to "#" do %>
              <span class="glyphicon glyphicon-globe icon" aria-hidden="true">
              </span>
            <% end %>
          </li>
          <li class="dropdown">
            <%= link_to "#", class: "dropdown-toggle", "data-toggle": "dropdown" do %>
              <%= @current_user.name %>
              <% if @current_user.avatar.nil? %>
                <%= image_tag "user_icon.png", class: "avatar" %>
              <% else %>
                <%= image_tag @current_user.avatar, class: "avatar" %>
              <% end %>
              <span class="caret"></span>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to t(".profile"), current_user %></li>
              <li><%= link_to t(".user"), users_path %></li>
              <li><%= link_to t(".settings"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t(".logout"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(".login"), login_path,
            data: {toggle: "modal", target: ".login-modal"} %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_login.html.erb
<div class="modal fade login-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="login">
        <div>
          <h2><%= t ".login" %></h2>
          <%= form_for :session, url: login_path do |f| %>
            <%= f.label :email %>
            <%= f.email_field :email, class: "form-control" %>

            <%= f.label :password %>
            <%= f.password_field :password, class: "form-control" %>

            <%= f.submit t ".login", class: "btn btn-primary" %>
          <% end %>
          <p> <%= t ".new" %><%= link_to t(".signup"), signup_path %></p>
        </div>
      <div>
  </div>
</div>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag "application", media: "all",
  "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "application", "data-turbolinks-track":
  "reload" %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= render "layouts/rails_default" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%= render "layouts/flash" %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
    <%= render "layouts/login" %>
  </body>
</html>